/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author ASUS
 */
public class LibroFisicoModificado extends javax.swing.JFrame {
    private String codigoDelLibro;      
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibroFisicoModificado.class.getName());

    /**
     * Creates new form LibroFisicoModificado
     */
    public LibroFisicoModificado(String codigoIngresado) {
        initComponents();
        this.codigoDelLibro = codigoIngresado;           

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        botonRegresarPrincipal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonModificarLibroDigital = new javax.swing.JButton();
        lblAutorDigital1 = new javax.swing.JLabel();
        txtAutorFisico = new javax.swing.JTextField();
        lblTituloFisico = new javax.swing.JLabel();
        txtTituloFisico = new javax.swing.JTextField();
        lblAnioPublicacionFisico = new javax.swing.JLabel();
        txtAnioPublicacionFisico = new javax.swing.JTextField();
        lblPasilloFisico = new javax.swing.JLabel();
        txtPasilloFisico = new javax.swing.JTextField();
        lblEstadoFisico = new javax.swing.JLabel();
        txtEstadoFisico = new javax.swing.JTextField();
        lblEstanteFisico = new javax.swing.JLabel();
        txtEstanteFisico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("Ingrese los datos que desea modificar del libro fisico");

        botonRegresarPrincipal.setText("REGRESAR");
        botonRegresarPrincipal.addActionListener(this::botonRegresarPrincipalActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(botonRegresarPrincipal)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(botonRegresarPrincipal))
                .addGap(11, 11, 11))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(19, 32, 45));

        botonModificarLibroDigital.setText("MODIFICAR");
        botonModificarLibroDigital.addActionListener(this::botonModificarLibroDigitalActionPerformed);

        lblAutorDigital1.setText("Autor");

        lblTituloFisico.setText("Titulo");

        lblAnioPublicacionFisico.setText("Año Publicacion");

        lblPasilloFisico.setText("Pasillo");

        lblEstadoFisico.setText("Estado");

        lblEstanteFisico.setText("Estante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(botonModificarLibroDigital)
                .addContainerGap(399, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblAutorDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAnioPublicacionFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(243, 243, 243))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTituloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(682, 682, 682))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTituloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAutorFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAnioPublicacionFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPasilloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPasilloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEstanteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEstanteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(70, 70, 70)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(98, 98, 98)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(botonModificarLibroDigital)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(lblAnioPublicacionFisico)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtAnioPublicacionFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPasilloFisico, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutorDigital1)
                            .addComponent(lblEstadoFisico)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAutorFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasilloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblTituloFisico)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTituloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEstanteFisico))
                    .addGap(14, 14, 14)
                    .addComponent(txtEstanteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarPrincipalActionPerformed
        // TODO add your handling code here:
        Vista ventanaPrincipal = new Vista();
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarPrincipalActionPerformed

    private void botonModificarLibroDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarLibroDigitalActionPerformed
        // TODO add your handling code here:
        String codigoBuscado = this.codigoDelLibro;
        //guardar temporalmente el registro anterior
        java.util.List<String> lineasArchivo = new java.util.ArrayList<>();
        boolean actualizado = false;

        try {
            BufferedReader br = new BufferedReader(new FileReader("LibrosFisicos.txt"));
            String linea;

            while ((linea = br.readLine()) != null) {
                String datos[] = linea.split(";");

                if (datos.length >= 6 && datos[0].equals(codigoBuscado)) {

                    String nuevoAutor = txtAutorFisico.getText().isEmpty() ? datos[1] : txtAutorFisico.getText();
                    String nuevoTitulo = txtTituloFisico.getText().isEmpty() ? datos[2] : txtTituloFisico.getText();
                    String nuevoAnio = txtAnioPublicacionFisico.getText().isEmpty() ? datos[3] : txtAnioPublicacionFisico.getText();
                    String nuevoPasillo = txtPasilloFisico.getText().isEmpty() ? datos[4] : txtPasilloFisico.getText();
                    String nuevoEstante = txtEstanteFisico.getText().isEmpty() ? datos[5] : txtEstanteFisico.getText();
                    String nuevoEstado = txtEstadoFisico.getText().isEmpty() ? datos[5] : txtEstadoFisico.getText();


                    String lineaModificada = datos[0] + ";" +
                    nuevoAutor + ";" +
                    nuevoTitulo + ";" +
                    nuevoAnio + ";" +
                    nuevoPasillo + ";" +
                    nuevoEstante + ";" +
                    nuevoEstado + ";";
                    lineasArchivo.add(lineaModificada);
                    actualizado = true;
                } else {
                    lineasArchivo.add(linea);
                }
            }
            br.close();
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el archivo base", "Mensaje del sistema", 0);
            return;
        }

        if (actualizado) {

            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter("LibrosFisicos.txt"));
                for (String lineasAGuardar : lineasArchivo) {
                    bw.write(lineasAGuardar);
                    bw.newLine();
                }
                bw.close();
                javax.swing.JOptionPane.showMessageDialog(this, "Libro Actualizado Correctamente", "Mensaje del sistema", 1);

                txtAutorFisico.setText("");
                txtTituloFisico.setText("");
                txtAnioPublicacionFisico.setText("");
                txtPasilloFisico.setText("");
                txtEstanteFisico.setText("");
                txtEstadoFisico.setText("");
            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ha ocurrido un error al guardar los cambios", "Mensaje del sistema", 0);
                System.out.println("Error al sobrescribir: " + e.getMessage());

            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el código del libro en la base de datos.", "Advertencia", 2);
        }
    }//GEN-LAST:event_botonModificarLibroDigitalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LibroFisicoModificado("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificarLibroDigital;
    private javax.swing.JButton botonRegresarPrincipal;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblAnioPublicacionFisico;
    private javax.swing.JLabel lblAutorDigital1;
    private javax.swing.JLabel lblEstadoFisico;
    private javax.swing.JLabel lblEstanteFisico;
    private javax.swing.JLabel lblPasilloFisico;
    private javax.swing.JLabel lblTituloFisico;
    private javax.swing.JTextField txtAnioPublicacionFisico;
    private javax.swing.JTextField txtAutorFisico;
    private javax.swing.JTextField txtEstadoFisico;
    private javax.swing.JTextField txtEstanteFisico;
    private javax.swing.JTextField txtPasilloFisico;
    private javax.swing.JTextField txtTituloFisico;
    // End of variables declaration//GEN-END:variables
}
