/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author ASUS
 */
public class LibroDigitalEncontrado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibroDigitalEncontrado.class.getName());

    /**
     * Creates new form LibroDigitalEncontrado
     */
    public LibroDigitalEncontrado(String codigoBuscado) {
        initComponents();
        
        boolean encontrado = false; 
        StringBuilder resultado = new StringBuilder();
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("LibrosDigitales.txt"));
            String linea;
            
            while ((linea = br.readLine()) != null) {
                String datos[] = linea.split(";");
                
                if (datos.length >= 6 && datos[0].equals(codigoBuscado)) {
                    resultado.append("=== LIBRO DIGITAL ENCONTRADO ===\n\n")
                             .append("CODIGO:    ").append(datos[0]).append("\n")
                             .append("AUTOR:    ").append(datos[1]).append("\n")
                             .append("TITULO:    ").append(datos[2]).append("\n")
                             .append("ANIO PUBLICACION:     ").append(datos[3]).append("\n")
                             .append("FORMATO ARCHIVO:     ").append(datos[4]).append("\n")
                             .append("TAMANIO MB:     ").append(datos[5]).append("\n");
                    encontrado = true; 
                    jTextAreaConsultaLibroDIgital.setText(resultado.toString());
                  break;
                }
            }
            br.close();
            if (!encontrado) {
                resultado.append("No se encontró ningún producto con el código: ").append(codigoBuscado);
                jTextAreaConsultaLibroDIgital.setText(resultado.toString());

            }       
        } catch (IOException e) {
            jTextAreaConsultaLibroDIgital.setText("Error al leer el archivo de base de datos.");
            System.out.println("Error: " + e.getMessage());           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsultaLibroDIgital = new javax.swing.JTextArea();
        botonRegresarPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 32, 45));

        jTextAreaConsultaLibroDIgital.setColumns(20);
        jTextAreaConsultaLibroDIgital.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsultaLibroDIgital);

        botonRegresarPrincipal.setText("Regresar Pestaña Principal");
        botonRegresarPrincipal.addActionListener(this::botonRegresarPrincipalActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(botonRegresarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegresarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarPrincipalActionPerformed
        // TODO add your handling code here:
        Vista ventanaPrincipal = new Vista();
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LibroDigitalEncontrado("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaConsultaLibroDIgital;
    // End of variables declaration//GEN-END:variables
}
