/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author ASUS
 */
public class LibroFisicoEncontrado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibroFisicoEncontrado.class.getName());

    /**
     * Creates new form LibroFisicoEncontrado
     */
    public LibroFisicoEncontrado(String codigoBuscado) {
        initComponents();
        
        boolean encontrado = false; 
        StringBuilder resultado = new StringBuilder();
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("LibrosDigitales.txt"));
            String linea;
            
            while ((linea = br.readLine()) != null) {
                String datos[] = linea.split(";");
        
                if (datos.length >= 7 && datos[0].equals(codigoBuscado)) {
                    resultado.append("=== LIBRO DIGITAL ENCONTRADO ===\n\n")
                             .append("CODIGO:    ").append(datos[0]).append("\n")
                             .append("AUTOR:    ").append(datos[1]).append("\n")
                             .append("TITULO:    ").append(datos[2]).append("\n")
                             .append("ANIO PUBLICACION:     ").append(datos[3]).append("\n")
                             .append("PASILLO:     ").append(datos[4]).append("\n")
                             .append("ESTANTE:     ").append(datos[5]).append("\n")
                             .append("ESTADO:     ").append(datos[6]).append("\n");
                    
                    encontrado = true; 
                    jTextAreaConsultaLibroFisico.setText(resultado.toString());
                    break;
                }
            }
            br.close();
            if (!encontrado) {
                resultado.append("No se encontró ningún producto con el código: ").append(codigoBuscado);
                jTextAreaConsultaLibroFisico.setText(resultado.toString());
            }      
        } catch (IOException e) {
            jTextAreaConsultaLibroFisico.setText("Error al leer el archivo de base de datos.");
            System.out.println("Error: " + e.getMessage());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresarPrincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsultaLibroFisico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonRegresarPrincipal.setText("Regresar Pestaña Principal");
        botonRegresarPrincipal.addActionListener(this::botonRegresarPrincipalActionPerformed);

        jTextAreaConsultaLibroFisico.setColumns(20);
        jTextAreaConsultaLibroFisico.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsultaLibroFisico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonRegresarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonRegresarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarPrincipalActionPerformed
        // TODO add your handling code here:
        Vista ventanaPrincipal = new Vista();
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LibroFisicoEncontrado("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaConsultaLibroFisico;
    // End of variables declaration//GEN-END:variables
}
