/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author ASUS
 */
public class LibroDigitalModificado extends javax.swing.JFrame {
    private String codigoDelLibro;  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibroDigitalModificado.class.getName());

    /**
     * Creates new form LibroDigitalModificado
     */
    public LibroDigitalModificado(String codigoIngresado) {     
            initComponents();
            this.codigoDelLibro = codigoIngresado;           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        botonRegresarPrincipal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonModificarLibroDigital = new javax.swing.JButton();
        lblAutorDigital = new javax.swing.JLabel();
        txtAutorDigital = new javax.swing.JTextField();
        lblTituloDigital = new javax.swing.JLabel();
        txtTituloDigital = new javax.swing.JTextField();
        lblAnioPublicacionDigital = new javax.swing.JLabel();
        txtAnioPublicacionDigital = new javax.swing.JTextField();
        lblFormatoArchivoDigital = new javax.swing.JLabel();
        txtFormatoArchivoDigital = new javax.swing.JTextField();
        lblTamanioMBDigital = new javax.swing.JLabel();
        txtTamanioMBDigital = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("Ingrese los datos que desea modificar del libro digital");

        botonRegresarPrincipal.setText("REGRESAR");
        botonRegresarPrincipal.addActionListener(this::botonRegresarPrincipalActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(botonRegresarPrincipal)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(botonRegresarPrincipal))
                .addGap(11, 11, 11))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(19, 32, 45));

        botonModificarLibroDigital.setText("MODIFICAR");
        botonModificarLibroDigital.addActionListener(this::botonModificarLibroDigitalActionPerformed);

        lblAutorDigital.setText("Autor");

        lblTituloDigital.setText("Titulo");

        lblAnioPublicacionDigital.setText("Año Publicacion");

        lblFormatoArchivoDigital.setText("Formato Archivo");

        lblTamanioMBDigital.setText("Tamaño MB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTituloDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(678, 678, 678))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTituloDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutorDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAnioPublicacionDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(388, 388, 388))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTamanioMBDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFormatoArchivoDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTamanioMBDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonModificarLibroDigital)
                                        .addGap(4, 4, 4)))
                                .addGap(395, 395, 395))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAutorDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFormatoArchivoDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnioPublicacionDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(354, 354, 354))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblAnioPublicacionDigital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAnioPublicacionDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorDigital)
                    .addComponent(lblFormatoArchivoDigital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAutorDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTituloDigital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTituloDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFormatoArchivoDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblTamanioMBDigital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTamanioMBDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102)
                .addComponent(botonModificarLibroDigital)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarLibroDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarLibroDigitalActionPerformed
        // TODO add your handling code here:
        String codigoBuscado = this.codigoDelLibro;
        //guardar temporalmente el registro anterior
        java.util.List<String> lineasArchivo = new java.util.ArrayList<>();
        boolean actualizado = false;
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("LibrosDigitales.txt"));
            String linea; 
            
            while ((linea = br.readLine()) != null) {
                String datos[] = linea.split(";");
                
                if (datos.length >= 6 && datos[0].equals(codigoBuscado)) {
                    
                    String nuevoAutor = txtAutorDigital.getText().isEmpty() ? datos[1] : txtAutorDigital.getText();
                    String nuevoTitulo = txtTituloDigital.getText().isEmpty() ? datos[2] : txtTituloDigital.getText();
                    String nuevoAnio = txtAnioPublicacionDigital.getText().isEmpty() ? datos[3] : txtAnioPublicacionDigital.getText();
                    String nuevoFormato = txtFormatoArchivoDigital.getText().isEmpty() ? datos[4] : txtFormatoArchivoDigital.getText();
                    String nuevoTamanio = txtTamanioMBDigital.getText().isEmpty() ? datos[5] : txtTamanioMBDigital.getText();    
                    
                    String lineaModificada = datos[0] + ";" +
                            nuevoAutor + ";" +
                            nuevoTitulo + ";" +
                            nuevoAnio + ";" +
                            nuevoFormato + ";" +
                            nuevoTamanio + ";";
                    lineasArchivo.add(lineaModificada);
                    actualizado = true; 
                } else {
                  lineasArchivo.add(linea);         
                }
            } 
            br.close();
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el archivo base", "Mensaje del sistema", 0);           
            return; 
        }
        
        if (actualizado) {
            
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter("LibrosDigitales.txt"));
                for (String lineasAGuardar : lineasArchivo) {
                    bw.write(lineasAGuardar);
                    bw.newLine();           
                }
                bw.close();
                javax.swing.JOptionPane.showMessageDialog(this, "Libro Actualizado Correctamente", "Mensaje del sistema", 1);

                txtAutorDigital.setText("");
                txtTituloDigital.setText("");
                txtAnioPublicacionDigital.setText("");
                txtFormatoArchivoDigital.setText("");
                txtTamanioMBDigital.setText("");              
            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ha ocurrido un error al guardar los cambios", "Mensaje del sistema", 0);
                System.out.println("Error al sobrescribir: " + e.getMessage());    

            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el código del libro en la base de datos.", "Advertencia", 2);     
        }       
    }//GEN-LAST:event_botonModificarLibroDigitalActionPerformed

    private void botonRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarPrincipalActionPerformed
        // TODO add your handling code here:
        Vista ventanaPrincipal = new Vista(); 
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LibroDigitalModificado("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificarLibroDigital;
    private javax.swing.JButton botonRegresarPrincipal;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblAnioPublicacionDigital;
    private javax.swing.JLabel lblAutorDigital;
    private javax.swing.JLabel lblFormatoArchivoDigital;
    private javax.swing.JLabel lblTamanioMBDigital;
    private javax.swing.JLabel lblTituloDigital;
    private javax.swing.JTextField txtAnioPublicacionDigital;
    private javax.swing.JTextField txtAutorDigital;
    private javax.swing.JTextField txtFormatoArchivoDigital;
    private javax.swing.JTextField txtTamanioMBDigital;
    private javax.swing.JTextField txtTituloDigital;
    // End of variables declaration//GEN-END:variables
}
