package Vista;


import Vista.AgregarLibro;
import Vista.BuscarLibroDigital;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());

    /**
     * Creates new form Principal
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        botonAgregarLibro = new javax.swing.JButton();
        botonBuscarLibro = new javax.swing.JButton();
        botonModificarLibro = new javax.swing.JButton();
        botonEliminarLibro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setPreferredSize(new java.awt.Dimension(212, 350));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        botonAgregarLibro.setBackground(new java.awt.Color(49, 80, 111));
        botonAgregarLibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonAgregarLibro.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarLibro.setText("AGREGAR UN LIBRO");
        botonAgregarLibro.addActionListener(this::botonAgregarLibroActionPerformed);
        jPanel5.add(botonAgregarLibro);

        botonBuscarLibro.setBackground(new java.awt.Color(49, 80, 111));
        botonBuscarLibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonBuscarLibro.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarLibro.setText("BUSCAR UN LIBRO");
        botonBuscarLibro.addActionListener(this::botonBuscarLibroActionPerformed);
        jPanel5.add(botonBuscarLibro);

        botonModificarLibro.setBackground(new java.awt.Color(49, 80, 111));
        botonModificarLibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonModificarLibro.setForeground(new java.awt.Color(255, 255, 255));
        botonModificarLibro.setText("MODIFICAR UN LIBRO");
        botonModificarLibro.addActionListener(this::botonModificarLibroActionPerformed);
        jPanel5.add(botonModificarLibro);

        botonEliminarLibro.setBackground(new java.awt.Color(49, 80, 111));
        botonEliminarLibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEliminarLibro.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarLibro.setText("ELIMINAR UN LIBRO");
        botonEliminarLibro.addActionListener(this::botonEliminarLibroActionPerformed);
        jPanel5.add(botonEliminarLibro);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(62, 32, 32));
        jPanel2.setPreferredSize(new java.awt.Dimension(527, 350));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(19, 32, 45));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE GESTIÓN DE BIBLIOTECA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarLibroActionPerformed
        // TODO add your handling code here:
        AgregarLibro ventanaAgregarLibro = new AgregarLibro();
        ventanaAgregarLibro.setVisible(true);
        this.setVisible(false);        
        
    }//GEN-LAST:event_botonAgregarLibroActionPerformed

    private void botonEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarLibroActionPerformed
        // TODO add your handling code here:
        EliminarLibro ventanaEliminarLibro = new EliminarLibro(); 
        ventanaEliminarLibro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonEliminarLibroActionPerformed

    private void botonBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarLibroActionPerformed
        // TODO add your handling code here:
        BuscarLibro ventanaBuscarLibro = new BuscarLibro();
        ventanaBuscarLibro.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonBuscarLibroActionPerformed

    private void botonModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarLibroActionPerformed
        // TODO add your handling code here:
        ModificarLibro ventanaModificarLibro = new ModificarLibro();
        ventanaModificarLibro.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_botonModificarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista().setVisible(true));
    }
// Hola mundo, no cmabien nada
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarLibro;
    private javax.swing.JButton botonBuscarLibro;
    private javax.swing.JButton botonEliminarLibro;
    private javax.swing.JButton botonModificarLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
