/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author ASUS
 */
public class AgregarLibroFisico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarLibroFisico.class.getName());

    /**
     * Creates new form AgregarLibroDigital
     */
    public AgregarLibroFisico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonRegresarRegistroLibroFisico = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblCodigoFisico = new javax.swing.JLabel();
        lblTituloFisico = new javax.swing.JLabel();
        lblAnioPublicacionFisico = new javax.swing.JLabel();
        lblPasilloFisico = new javax.swing.JLabel();
        lblAutorDigital = new javax.swing.JLabel();
        lblEstanteFisico = new javax.swing.JLabel();
        txtCodigoFisico = new javax.swing.JTextField();
        txtAutorFisico = new javax.swing.JTextField();
        txtTituloFisico = new javax.swing.JTextField();
        txtAnioPublicacionFisico = new javax.swing.JTextField();
        txtPasilloFisico = new javax.swing.JTextField();
        txtEstanteFisico = new javax.swing.JTextField();
        botonRegistrarLibroFisico = new javax.swing.JButton();
        lblEstadoFisico = new javax.swing.JLabel();
        txtEstadoFisico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 80, 111));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(19, 32, 45));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO LIBRO FISICO");

        botonRegresarRegistroLibroFisico.setText("Regresar");
        botonRegresarRegistroLibroFisico.addActionListener(this::botonRegresarRegistroLibroFisicoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(191, 191, 191)
                .addComponent(botonRegresarRegistroLibroFisico)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRegresarRegistroLibroFisico)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(49, 80, 111));

        lblCodigoFisico.setText("Codigo");

        lblTituloFisico.setText("Titulo");

        lblAnioPublicacionFisico.setText("Año Publicacion");

        lblPasilloFisico.setText("Pasillo");

        lblAutorDigital.setText("Autor");

        lblEstanteFisico.setText("Estante");

        botonRegistrarLibroFisico.setText("REGISTRAR");
        botonRegistrarLibroFisico.addActionListener(this::botonRegistrarLibroFisicoActionPerformed);

        lblEstadoFisico.setText("Estado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAutorDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnioPublicacionFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTituloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutorFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(botonRegistrarLibroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 374, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAnioPublicacionFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPasilloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPasilloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEstanteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEstanteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(83, 83, 83))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTituloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoFisico)
                    .addComponent(lblAnioPublicacionFisico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnioPublicacionFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPasilloFisico, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAutorDigital)
                        .addComponent(lblEstadoFisico)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAutorFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPasilloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloFisico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstanteFisico))
                .addGap(14, 14, 14)
                .addComponent(txtEstanteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegistrarLibroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarLibroFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarLibroFisicoActionPerformed
        // TODO add your handling code here:
        
        if (txtCodigoFisico.getText().equals("") ||
            txtAutorFisico.getText().equals("") || 
            txtTituloFisico.getText().equals("") ||
            txtAnioPublicacionFisico.getText().equals("") ||
            txtPasilloFisico.getText().equals("") ||
            txtEstanteFisico.getText().equals("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Mensaje del Sistema",0); 
            return;
        }
        
        try {
        BufferedWriter bw = new BufferedWriter(new FileWriter("LibrosFisicos.txt", true));
            bw.write(txtCodigoFisico.getText() + ";" +
            txtAutorFisico.getText() + ";" +
            txtTituloFisico.getText() + ";" +
            txtAnioPublicacionFisico.getText() + ";" +
            txtPasilloFisico.getText() + ";" +
            txtEstanteFisico.getText()+ ";" +
            txtEstadoFisico.getText() + ";" 
            );
            bw.newLine();
            bw.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Libro Guardado", "mensaje del sistema", 1);
        
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ha ocurrido un error al guuardar el libro", "mensaje del sistema", 0);
            System.out.println("Error al guardar el producto electronico" + e.getMessage());   
        }
        
        txtCodigoFisico.setText("");
        txtAutorFisico.setText(""); 
        txtTituloFisico.setText(""); 
        txtAnioPublicacionFisico.setText(""); 
        txtPasilloFisico.setText(""); 
        txtEstanteFisico.setText(""); 
        txtEstadoFisico.setText("");
    }//GEN-LAST:event_botonRegistrarLibroFisicoActionPerformed

    private void botonRegresarRegistroLibroFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarRegistroLibroFisicoActionPerformed
        // TODO add your handling code here:
        Vista ventanaPrincipal = new Vista(); 
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonRegresarRegistroLibroFisicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgregarLibroFisico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrarLibroFisico;
    private javax.swing.JButton botonRegresarRegistroLibroFisico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAnioPublicacionFisico;
    private javax.swing.JLabel lblAutorDigital;
    private javax.swing.JLabel lblCodigoFisico;
    private javax.swing.JLabel lblEstadoFisico;
    private javax.swing.JLabel lblEstanteFisico;
    private javax.swing.JLabel lblPasilloFisico;
    private javax.swing.JLabel lblTituloFisico;
    private javax.swing.JTextField txtAnioPublicacionFisico;
    private javax.swing.JTextField txtAutorFisico;
    private javax.swing.JTextField txtCodigoFisico;
    private javax.swing.JTextField txtEstadoFisico;
    private javax.swing.JTextField txtEstanteFisico;
    private javax.swing.JTextField txtPasilloFisico;
    private javax.swing.JTextField txtTituloFisico;
    // End of variables declaration//GEN-END:variables
}
