/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author ASUS
 */
public class AgregarLibro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarLibro.class.getName());

    /**
     * Creates new form AgregarLibro
     */
    public AgregarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonRegresarPrincipal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonLibroDigital = new javax.swing.JButton();
        botonLibroFisico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(19, 32, 45));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ELEGIR EL TIPO DE LIBRO A AGREGAR");

        botonRegresarPrincipal.setText("REGRESAR");
        botonRegresarPrincipal.addActionListener(this::botonRegresarPrincipalActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(botonRegresarPrincipal)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRegresarPrincipal)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        botonLibroDigital.setBackground(new java.awt.Color(49, 80, 111));
        botonLibroDigital.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonLibroDigital.setText("LIBRO DIGITAL");
        botonLibroDigital.addActionListener(this::botonLibroDigitalActionPerformed);
        jPanel1.add(botonLibroDigital);

        botonLibroFisico.setBackground(new java.awt.Color(49, 80, 111));
        botonLibroFisico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonLibroFisico.setText("LIBRO FISICO");
        botonLibroFisico.addActionListener(this::botonLibroFisicoActionPerformed);
        jPanel1.add(botonLibroFisico);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLibroFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLibroFisicoActionPerformed
        // TODO add your handling code here:
        AgregarLibroFisico ventanaAgregarLibroFisico = new AgregarLibroFisico();
        ventanaAgregarLibroFisico.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonLibroFisicoActionPerformed

    private void botonLibroDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLibroDigitalActionPerformed
        // TODO add your handling code here:
        AgregarLibroDigital ventanaAgregarLibroDigital = new AgregarLibroDigital();
        ventanaAgregarLibroDigital.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_botonLibroDigitalActionPerformed

    private void botonRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarPrincipalActionPerformed
        // TODO add your handling code here:
        Vista ventanaPrincipal = new Vista();
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgregarLibro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLibroDigital;
    private javax.swing.JButton botonLibroFisico;
    private javax.swing.JButton botonRegresarPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
