/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author ASUS
 */
public class EliminarLibroFisico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EliminarLibroFisico.class.getName());

    /**
     * Creates new form EliminarLibroFisico
     */
    public EliminarLibroFisico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonRegresarPrincipal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoLibroFisico = new javax.swing.JTextField();
        lblCodigoLibroFisico = new javax.swing.JLabel();
        botonEliminarLibroFisico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INGRESE EL CODIGO DEL LIBRO FISICO QUE DESEA ELIMINAR:");

        botonRegresarPrincipal.setText("REGRESAR");
        botonRegresarPrincipal.addActionListener(this::botonRegresarPrincipalActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(botonRegresarPrincipal)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botonRegresarPrincipal))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(49, 80, 111));

        txtCodigoLibroFisico.addActionListener(this::txtCodigoLibroFisicoActionPerformed);

        lblCodigoLibroFisico.setText("CODIGO LIBRO FISICO");

        botonEliminarLibroFisico.setText("ELIMINAR");
        botonEliminarLibroFisico.addActionListener(this::botonEliminarLibroFisicoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoLibroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoLibroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(botonEliminarLibroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblCodigoLibroFisico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoLibroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(botonEliminarLibroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarPrincipalActionPerformed
        // TODO add your handling code here:
        Vista ventanaPrincipal = new Vista();
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarPrincipalActionPerformed

    private void txtCodigoLibroFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoLibroFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoLibroFisicoActionPerformed

    private void botonEliminarLibroFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarLibroFisicoActionPerformed
        // TODO add your handling code here:
        String codigoIngresado = txtCodigoLibroFisico.getText();

        if (codigoIngresado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un código para eliminar.", "Advertencia", 2);
            return;
        }
        // Lista temporal para guardar todos los registros que NO queremos borrar
        java.util.List<String> lineasRestantes = new java.util.ArrayList<>();
        boolean eliminado = false;

        try {
            BufferedReader br = new BufferedReader(new FileReader("LibrosFisicos.txt"));
            String linea;

            while ((linea = br.readLine()) != null) {
                String datos[] = linea.split(";");

                if (datos.length >= 1 && datos[0].equals(codigoIngresado)) {
                    eliminado = true;
                } else {
                    lineasRestantes.add(linea);
                }
            }
            br.close();

        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el archivo de base de datos.", "Error del Sistema", 0);            System.out.println("Error: " + e.getMessage());
            System.out.println("Error: " + e.getMessage());
            return;
        }

        if (eliminado) {
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter("LibrosFisicos.txt"));
                for (String lineaAGuardar : lineasRestantes) {
                    bw.write(lineaAGuardar);
                    bw.newLine();
                }
                bw.close();

                javax.swing.JOptionPane.showMessageDialog(this, "El libro con código [" + codigoIngresado + "] ha sido eliminado.", "Mensaje del Sistema", 1);

                txtCodigoLibroFisico.setText("");

            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar los cambios en el archivo.", "Error del Sistema", 0);
                System.out.println("Error al escribir: " + e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún libro con el código: " + codigoIngresado, "Advertencia", 2);
        }
    }//GEN-LAST:event_botonEliminarLibroFisicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EliminarLibroFisico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarLibroFisico;
    private javax.swing.JButton botonRegresarPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCodigoLibroFisico;
    private javax.swing.JTextField txtCodigoLibroFisico;
    // End of variables declaration//GEN-END:variables
}
